# Generated by Django 3.0.5 on 2020-04-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_platter_type', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta_type', models.CharField(max_length=64)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad_type', models.CharField(max_length=64)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
                ('add_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('cost', models.FloatField()),
                ('toppings', models.ManyToManyField(blank=True, related_name='toppings', to='orders.SubToppings')),
            ],
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('num_toppings', models.PositiveSmallIntegerField()),
                ('cost', models.FloatField()),
                ('toppings', models.ManyToManyField(blank=True, related_name='sicilian_pizza_toppings', to='orders.PizzaToppings')),
            ],
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('num_toppings', models.PositiveSmallIntegerField()),
                ('cost', models.FloatField()),
                ('toppings', models.ManyToManyField(blank=True, related_name='regular_pizza_toppings', to='orders.PizzaToppings')),
            ],
        ),
    ]
