# Generated by Django 3.0.5 on 2020-04-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200405_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinnerplatter',
            options={'verbose_name_plural': '8. Dinner Platter'},
        ),
        migrations.AlterModelOptions(
            name='pasta',
            options={'verbose_name_plural': '6. Pasta'},
        ),
        migrations.AlterModelOptions(
            name='pizzatopping',
            options={'verbose_name_plural': '1. Pizza Toppings'},
        ),
        migrations.AlterModelOptions(
            name='regularpizza',
            options={'verbose_name_plural': '2. Regular Pizza'},
        ),
        migrations.AlterModelOptions(
            name='salad',
            options={'verbose_name_plural': '7. Salad'},
        ),
        migrations.AlterModelOptions(
            name='sicilianpizza',
            options={'verbose_name_plural': '3. Sicilian Pizza'},
        ),
        migrations.AlterModelOptions(
            name='sub',
            options={'verbose_name_plural': '5. Subs'},
        ),
        migrations.AlterModelOptions(
            name='subtopping',
            options={'verbose_name_plural': '4. Sub Toppings'},
        ),
    ]
