# Generated by Django 3.0.5 on 2020-04-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200406_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='SubTopping',
        ),
    ]
