# Generated by Django 3.0.5 on 2020-04-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200410_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='num_toppings',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
