# Generated by Django 3.0.5 on 2020-04-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200410_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActiveOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Orders')),
            ],
        ),
    ]
