# Generated by Django 3.0.5 on 2020-04-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200411_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeorders',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
