# Generated by Django 3.0.5 on 2020-04-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200411_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pizza_toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.PizzaTopping'),
        ),
    ]
